server:
      PORT: 3000
      JWT_SECRET: 'a7f07643cdc0f503596d5a28390b678c653a4dd0060edf328d86ebc7ca2c3578b720ed503aa8f67d6d41d1913c11993437334ebe88e7cb4ab22f70216d5a8493'
database:
      HOST: localhost
      PORT: 3306
      NAME: quickpickdb
      USERNAME: root
      PASSWORD: ''
      ADMIN_ONE: 'groot'
      ADMIN_ONE_PASSWORD: '$2b$10$3fbVVKtB4YI4NTD3WbKcVeo5av6DbHd3ovrS7U3OIwJ0VVZJvbaeS'
      ADMIN_TWO: 'beetroot'
      ADMIN_TWO_PASSWORD: '$2b$10$4xfsqHIFFgJ9TaGad/JWL.XDZXKExbDKLQ8c8odwUatdW7vspvYGi'
